modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ArcAnc/nedaire-1.19/issues/"
[[mods]]
modId="${modId}"
version="${version}"
displayName="Nedaire"
displayURL="https://github.com/ArcAnc/nedaire-1.19/"
logoFile="nedaire_logo.png"
credits="Thanks for this to Java and for me, of course"
authors="ArcAnc"
description='''
Nedaire is big mod Techno Magic mod for Minecraft with a focus on perfomance and really interesting content
'''
[[dependencies.nedaire]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.nedaire]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="BEFORE"
    side="BOTH"
